image: docker:latest

services:
  - docker:dind

before_script:
  - docker info

build:
  stage: build
  before_script:
    - echo $DOCKER_USERNAME
    - docker login --username ${CI_REGISTRY_USER} --password ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - docker build --pull -t ${CI_REGISTRY_IMAGE} .
    - docker push ${CI_REGISTRY_IMAGE}
  after_script:
    - docker logout
  only:
    - master

