image: docker:latest

services:
  - docker:dind

before_script:
  - docker info

build:
  stage: build
  before_script:
    - docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
  script:
    - docker build -t gitlab-ci/ruby-build:latest .
    - docker push azadehafzarhub/gitlab-ci-ruby-build
  after_script:
    - docker logout
  only:
    - master

